# This is a basic workflow to help you get started with Actions

name: Latest blog post workflow

# Controls when the workflow will run
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
      workflow_dispatch:
      
jobs:
  update-readme-with-blog:
    name: Update this repos README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isabeljohnson001/About@isabeljohnson001-main
        with:
          max_post_count: "4"
          feed_list: "https://www.linkedin.com/in/isabeljohnson06/"



